export const grid_height = 10;
export const grid_width = 10;
export const start_x_pos = 40;
export const start_y_pos = 40;
export const cell_delta_x = 64;
export const cell_delta_y = 64;
export const type_colors = ['black', 'green', 'blue', 'yellow', 'white'];
export const cell_width = 64;
export const cell_height = 64;